<?php

/**
 * Sidebar menu. Each item: label, route, icon (bootstrap-icons), roles.
 * Route null => section header.
 */
return [
    ['section' => 'Main'],
    ['label' => 'Dashboard', 'route' => 'dashboard', 'icon' => 'bi-speedometer2', 'roles' => ['admin', 'accountant', 'teacher', 'student', 'parent']],

    ['section' => 'Administration', 'roles' => ['admin']],
    ['label' => 'Admission Query', 'route' => 'admission-queries.index', 'icon' => 'bi-question-circle', 'roles' => ['admin']],
    ['label' => 'Visitor Book', 'route' => 'visitor-books.index', 'icon' => 'bi-journal-text', 'roles' => ['admin']],
    ['label' => 'Phone Call Log', 'route' => 'phone-call-logs.index', 'icon' => 'bi-telephone', 'roles' => ['admin']],
    ['label' => 'Postal Receive', 'route' => 'postal-receives.index', 'icon' => 'bi-inbox', 'roles' => ['admin']],
    ['label' => 'Postal Dispatch', 'route' => 'postal-dispatches.index', 'icon' => 'bi-send', 'roles' => ['admin']],
    ['label' => 'Complaints', 'route' => 'complaints.index', 'icon' => 'bi-exclamation-circle', 'roles' => ['admin']],
    ['label' => 'Certificates', 'route' => 'student-certificates.index', 'icon' => 'bi-award', 'roles' => ['admin']],
    ['label' => 'Generate Certificate', 'route' => 'certificates.generate', 'icon' => 'bi-award-fill', 'roles' => ['admin']],
    ['label' => 'ID Cards', 'route' => 'id-cards.index', 'icon' => 'bi-person-badge', 'roles' => ['admin']],
    ['label' => 'Generate ID Card', 'route' => 'id-cards.generate', 'icon' => 'bi-person-badge-fill', 'roles' => ['admin']],

    ['section' => 'Student Info', 'roles' => ['admin', 'teacher']],
    ['label' => 'Student Category', 'route' => 'student-categories.index', 'icon' => 'bi-tags', 'roles' => ['admin']],
    ['label' => 'Add Student', 'route' => 'students.create', 'icon' => 'bi-person-plus', 'roles' => ['admin']],
    ['label' => 'Student List', 'route' => 'students.index', 'icon' => 'bi-people', 'roles' => ['admin', 'teacher']],
    ['label' => 'Student Attendance', 'route' => 'attendance.student', 'icon' => 'bi-check2-square', 'roles' => ['admin', 'teacher']],
    ['label' => 'Attendance Report', 'route' => 'attendance.student.report', 'icon' => 'bi-clipboard-data', 'roles' => ['admin', 'teacher']],
    ['label' => 'Subject Wise Attendance', 'route' => 'attendance.subject', 'icon' => 'bi-journal-check', 'roles' => ['admin', 'teacher']],
    ['label' => 'Subject Attendance Report', 'route' => 'attendance.subject.report', 'icon' => 'bi-clipboard2-data', 'roles' => ['admin', 'teacher']],
    ['label' => 'Student Group', 'route' => 'student-groups.index', 'icon' => 'bi-collection', 'roles' => ['admin']],
    ['label' => 'Student Promote', 'route' => 'students.promote', 'icon' => 'bi-arrow-up-circle', 'roles' => ['admin']],
    ['label' => 'Disabled Students', 'route' => 'students.disabled', 'icon' => 'bi-person-x', 'roles' => ['admin']],

    ['section' => 'Academics', 'roles' => ['admin', 'teacher']],
    ['label' => 'Classes', 'route' => 'classes.index', 'icon' => 'bi-building', 'roles' => ['admin']],
    ['label' => 'Sections', 'route' => 'sections.index', 'icon' => 'bi-diagram-3', 'roles' => ['admin']],
    ['label' => 'Subjects', 'route' => 'subjects.index', 'icon' => 'bi-book', 'roles' => ['admin']],
    ['label' => 'Optional Subjects', 'route' => 'optional-subjects.index', 'icon' => 'bi-journal-plus', 'roles' => ['admin']],
    ['label' => 'Assign Class Teacher', 'route' => 'assign-class-teachers.index', 'icon' => 'bi-person-check', 'roles' => ['admin']],
    ['label' => 'Assign Subject', 'route' => 'assign-subjects.index', 'icon' => 'bi-journal-arrow-up', 'roles' => ['admin']],
    ['label' => 'Class Rooms', 'route' => 'class-rooms.index', 'icon' => 'bi-door-open', 'roles' => ['admin']],
    ['label' => 'Class Time Setup', 'route' => 'class-times.index', 'icon' => 'bi-clock', 'roles' => ['admin']],
    ['label' => 'Class Routine', 'route' => 'class-routines.index', 'icon' => 'bi-calendar3-week', 'roles' => ['admin', 'teacher']],

    ['section' => 'Study Material', 'roles' => ['admin', 'teacher', 'student']],
    ['label' => 'Upload Content', 'route' => 'upload-contents.index', 'icon' => 'bi-cloud-upload', 'roles' => ['admin', 'teacher']],
    ['label' => 'Assignments', 'route' => 'study-material.assignments', 'icon' => 'bi-pencil-square', 'roles' => ['admin', 'teacher', 'student']],
    ['label' => 'Study Material', 'route' => 'study-material.materials', 'icon' => 'bi-journal-richtext', 'roles' => ['admin', 'teacher', 'student']],
    ['label' => 'Syllabus', 'route' => 'study-material.syllabus', 'icon' => 'bi-list-columns', 'roles' => ['admin', 'teacher', 'student']],
    ['label' => 'Other Downloads', 'route' => 'study-material.downloads', 'icon' => 'bi-download', 'roles' => ['admin', 'teacher', 'student']],

    ['section' => 'Lesson Plan', 'roles' => ['admin', 'teacher']],
    ['label' => 'Lessons', 'route' => 'lessons.index', 'icon' => 'bi-journal-bookmark', 'roles' => ['admin', 'teacher']],
    ['label' => 'Topics', 'route' => 'topics.index', 'icon' => 'bi-list-ol', 'roles' => ['admin', 'teacher']],
    ['label' => 'Lesson Plans', 'route' => 'lesson-plans.index', 'icon' => 'bi-calendar2-check', 'roles' => ['admin', 'teacher']],

    ['section' => 'Fees Collection', 'roles' => ['admin', 'accountant']],
    ['label' => 'Fees Group', 'route' => 'fees-groups.index', 'icon' => 'bi-collection-fill', 'roles' => ['admin', 'accountant']],
    ['label' => 'Fees Type', 'route' => 'fees-types.index', 'icon' => 'bi-tag', 'roles' => ['admin', 'accountant']],
    ['label' => 'Fees Master', 'route' => 'fees-masters.index', 'icon' => 'bi-cash-stack', 'roles' => ['admin', 'accountant']],
    ['label' => 'Fees Discount', 'route' => 'fees-discounts.index', 'icon' => 'bi-percent', 'roles' => ['admin', 'accountant']],
    ['label' => 'Collect Fees', 'route' => 'fees.collect', 'icon' => 'bi-cash-coin', 'roles' => ['admin', 'accountant']],
    ['label' => 'Search Fees Payment', 'route' => 'fees.search-payment', 'icon' => 'bi-search', 'roles' => ['admin', 'accountant']],
    ['label' => 'Search Fees Dues', 'route' => 'fees.search-dues', 'icon' => 'bi-search-heart', 'roles' => ['admin', 'accountant']],
    ['label' => 'Bank Payments', 'route' => 'bank-payments.index', 'icon' => 'bi-bank', 'roles' => ['admin', 'accountant']],
    ['label' => 'Fees Carry Forward', 'route' => 'fees-carry-forwards.index', 'icon' => 'bi-arrow-right-circle', 'roles' => ['admin', 'accountant']],
    ['label' => 'Collection Report', 'route' => 'fees.collection-report', 'icon' => 'bi-bar-chart', 'roles' => ['admin', 'accountant']],
    ['label' => 'Monthly Collection', 'route' => 'fees.monthly-report', 'icon' => 'bi-bar-chart-line', 'roles' => ['admin', 'accountant']],

    ['section' => 'Accounts', 'roles' => ['admin', 'accountant']],
    ['label' => 'Account Dashboard', 'route' => 'accounts.dashboard', 'icon' => 'bi-wallet2', 'roles' => ['admin', 'accountant']],
    ['label' => 'Income', 'route' => 'incomes.index', 'icon' => 'bi-graph-up-arrow', 'roles' => ['admin', 'accountant']],
    ['label' => 'Expense', 'route' => 'expenses.index', 'icon' => 'bi-graph-down-arrow', 'roles' => ['admin', 'accountant']],
    ['label' => 'Account List', 'route' => 'accounts.index', 'icon' => 'bi-list-ul', 'roles' => ['admin', 'accountant']],
    ['label' => 'Payment Methods', 'route' => 'payment-methods.index', 'icon' => 'bi-credit-card', 'roles' => ['admin', 'accountant']],
    ['label' => 'Bank Accounts', 'route' => 'bank-accounts.index', 'icon' => 'bi-bank2', 'roles' => ['admin', 'accountant']],
    ['label' => 'Payment History', 'route' => 'accounts.payment-history', 'icon' => 'bi-clock-history', 'roles' => ['admin', 'accountant']],

    ['section' => 'Human Resource', 'roles' => ['admin']],
    ['label' => 'Staff Directory', 'route' => 'staff.index', 'icon' => 'bi-person-lines-fill', 'roles' => ['admin']],
    ['label' => 'Staff Attendance', 'route' => 'attendance.staff', 'icon' => 'bi-check2-all', 'roles' => ['admin']],
    ['label' => 'Staff Attendance Report', 'route' => 'attendance.staff.report', 'icon' => 'bi-clipboard2-pulse', 'roles' => ['admin']],
    ['label' => 'Payroll', 'route' => 'payrolls.index', 'icon' => 'bi-cash', 'roles' => ['admin']],
    ['label' => 'Payroll Report', 'route' => 'payrolls.report', 'icon' => 'bi-file-earmark-bar-graph', 'roles' => ['admin']],

    ['section' => 'Examination', 'roles' => ['admin', 'teacher']],
    ['label' => 'Marks Grade', 'route' => 'marks-grades.index', 'icon' => 'bi-sort-alpha-down', 'roles' => ['admin']],
    ['label' => 'Exam Type', 'route' => 'exam-types.index', 'icon' => 'bi-ui-radios', 'roles' => ['admin']],
    ['label' => 'Exam Setup', 'route' => 'exams.index', 'icon' => 'bi-gear', 'roles' => ['admin']],
    ['label' => 'Exam Schedule', 'route' => 'exam-schedules.index', 'icon' => 'bi-calendar2-event', 'roles' => ['admin', 'teacher']],
    ['label' => 'Exam Attendance', 'route' => 'exam-attendances.index', 'icon' => 'bi-check2-circle', 'roles' => ['admin', 'teacher']],
    ['label' => 'Mark Register', 'route' => 'marks.register', 'icon' => 'bi-pencil', 'roles' => ['admin', 'teacher']],
    ['label' => 'Send Marks by SMS', 'route' => 'marks.send-sms', 'icon' => 'bi-chat-dots', 'roles' => ['admin']],

    ['section' => 'Online Exam', 'roles' => ['admin', 'teacher', 'student']],
    ['label' => 'Question Bank', 'route' => 'question-banks.index', 'icon' => 'bi-question-square', 'roles' => ['admin', 'teacher']],
    ['label' => 'Online Exams', 'route' => 'online-exams.index', 'icon' => 'bi-laptop', 'roles' => ['admin', 'teacher', 'student']],

    ['section' => 'Homework', 'roles' => ['admin', 'teacher', 'student', 'parent']],
    ['label' => 'Add Homework', 'route' => 'homeworks.create', 'icon' => 'bi-plus-square', 'roles' => ['admin', 'teacher']],
    ['label' => 'Homework List', 'route' => 'homeworks.index', 'icon' => 'bi-card-list', 'roles' => ['admin', 'teacher', 'student', 'parent']],
    ['label' => 'Evaluation Report', 'route' => 'homeworks.evaluation', 'icon' => 'bi-clipboard-check', 'roles' => ['admin', 'teacher']],

    ['section' => 'Communication', 'roles' => ['admin', 'teacher', 'student', 'parent']],
    ['label' => 'Chat Box', 'route' => 'chat.index', 'icon' => 'bi-chat-left-text', 'roles' => ['admin', 'teacher', 'student', 'parent']],
    ['label' => 'Notice Board', 'route' => 'notices.index', 'icon' => 'bi-megaphone', 'roles' => ['admin', 'teacher', 'student', 'parent']],
    ['label' => 'Send Message', 'route' => 'messages.index', 'icon' => 'bi-envelope', 'roles' => ['admin', 'teacher', 'student', 'parent']],
    ['label' => 'Email / SMS Log', 'route' => 'email-sms.index', 'icon' => 'bi-envelope-paper', 'roles' => ['admin']],
    ['label' => 'Events', 'route' => 'events.index', 'icon' => 'bi-calendar-event', 'roles' => ['admin', 'teacher', 'student', 'parent']],
    ['label' => 'Holidays', 'route' => 'holidays.index', 'icon' => 'bi-sun', 'roles' => ['admin', 'teacher', 'student', 'parent']],

    ['section' => 'Library', 'roles' => ['admin']],
    ['label' => 'Book Categories', 'route' => 'book-categories.index', 'icon' => 'bi-tags', 'roles' => ['admin']],
    ['label' => 'Books', 'route' => 'books.index', 'icon' => 'bi-book-half', 'roles' => ['admin']],
    ['label' => 'Library Members', 'route' => 'library-members.index', 'icon' => 'bi-person-vcard', 'roles' => ['admin']],
    ['label' => 'Issue / Return Book', 'route' => 'book-issues.index', 'icon' => 'bi-arrow-left-right', 'roles' => ['admin']],
    ['label' => 'All Issued Books', 'route' => 'book-issues.issued', 'icon' => 'bi-journal-arrow-down', 'roles' => ['admin']],

    ['section' => 'Inventory', 'roles' => ['admin']],
    ['label' => 'Item Category', 'route' => 'item-categories.index', 'icon' => 'bi-tags', 'roles' => ['admin']],
    ['label' => 'Items', 'route' => 'items.index', 'icon' => 'bi-box', 'roles' => ['admin']],
    ['label' => 'Item Store', 'route' => 'item-stores.index', 'icon' => 'bi-shop', 'roles' => ['admin']],
    ['label' => 'Suppliers', 'route' => 'suppliers.index', 'icon' => 'bi-truck', 'roles' => ['admin']],
    ['label' => 'Item Receive', 'route' => 'item-receives.index', 'icon' => 'bi-box-arrow-in-down', 'roles' => ['admin']],
    ['label' => 'Item Sell', 'route' => 'item-sells.index', 'icon' => 'bi-cash-register', 'roles' => ['admin']],
    ['label' => 'Item Issue', 'route' => 'item-issues.index', 'icon' => 'bi-box-arrow-up', 'roles' => ['admin']],

    ['section' => 'Transport', 'roles' => ['admin']],
    ['label' => 'Routes', 'route' => 'transport-routes.index', 'icon' => 'bi-signpost', 'roles' => ['admin']],
    ['label' => 'Vehicles', 'route' => 'vehicles.index', 'icon' => 'bi-bus-front', 'roles' => ['admin']],
    ['label' => 'Assign Vehicle', 'route' => 'assign-vehicles.index', 'icon' => 'bi-person-rolodex', 'roles' => ['admin']],
    ['label' => 'Student Transport Report', 'route' => 'transport.report', 'icon' => 'bi-file-earmark-text', 'roles' => ['admin']],

    ['section' => 'Dormitory', 'roles' => ['admin']],
    ['label' => 'Dormitories', 'route' => 'dormitories.index', 'icon' => 'bi-houses', 'roles' => ['admin']],
    ['label' => 'Room Types', 'route' => 'room-types.index', 'icon' => 'bi-grid', 'roles' => ['admin']],
    ['label' => 'Dormitory Rooms', 'route' => 'dormitory-rooms.index', 'icon' => 'bi-door-closed', 'roles' => ['admin']],
    ['label' => 'Rooms Monitoring', 'route' => 'dormitory.monitoring', 'icon' => 'bi-display', 'roles' => ['admin']],
    ['label' => 'Student Dormitory Report', 'route' => 'dormitory.report', 'icon' => 'bi-file-earmark-person', 'roles' => ['admin']],

    ['section' => 'Reports', 'roles' => ['admin']],
    ['label' => 'Student Report', 'route' => 'reports.student', 'icon' => 'bi-file-person', 'roles' => ['admin']],
    ['label' => 'Guardian Report', 'route' => 'reports.guardian', 'icon' => 'bi-file-person-check', 'roles' => ['admin']],
    ['label' => 'Student History', 'route' => 'reports.student-history', 'icon' => 'bi-clock-history', 'roles' => ['admin']],
    ['label' => 'Login Report', 'route' => 'reports.login', 'icon' => 'bi-box-arrow-in-right', 'roles' => ['admin']],
    ['label' => 'Fees Statement', 'route' => 'reports.fees-statement', 'icon' => 'bi-receipt', 'roles' => ['admin']],
    ['label' => 'Balance Fees Report', 'route' => 'reports.balance-fees', 'icon' => 'bi-receipt-cutoff', 'roles' => ['admin']],
    ['label' => 'Class Report', 'route' => 'reports.class', 'icon' => 'bi-file-earmark-spreadsheet', 'roles' => ['admin']],
    ['label' => 'Class Routine', 'route' => 'reports.class-routine', 'icon' => 'bi-calendar3', 'roles' => ['admin']],
    ['label' => 'Exam Routine', 'route' => 'reports.exam-routine', 'icon' => 'bi-calendar2-range', 'roles' => ['admin']],
    ['label' => 'Teacher Class Routine', 'route' => 'reports.teacher-routine', 'icon' => 'bi-calendar2-week', 'roles' => ['admin']],
    ['label' => 'Merit List', 'route' => 'reports.merit-list', 'icon' => 'bi-trophy', 'roles' => ['admin']],
    ['label' => 'Online Exam Report', 'route' => 'reports.online-exam', 'icon' => 'bi-laptop', 'roles' => ['admin']],
    ['label' => 'Mark Sheet', 'route' => 'reports.mark-sheet', 'icon' => 'bi-file-earmark-ruled', 'roles' => ['admin']],
    ['label' => 'Tabulation Sheet', 'route' => 'reports.tabulation', 'icon' => 'bi-table', 'roles' => ['admin']],
    ['label' => 'Progress Card', 'route' => 'reports.progress-card', 'icon' => 'bi-file-earmark-medical', 'roles' => ['admin']],
    ['label' => 'User Log', 'route' => 'reports.user-log', 'icon' => 'bi-person-clock', 'roles' => ['admin']],
    ['label' => 'Previous Result', 'route' => 'reports.previous-result', 'icon' => 'bi-archive', 'roles' => ['admin']],

    ['section' => 'System Settings', 'roles' => ['admin']],
    ['label' => 'General Settings', 'route' => 'settings.general', 'icon' => 'bi-sliders', 'roles' => ['admin']],
    ['label' => 'Academic Years', 'route' => 'academic-years.index', 'icon' => 'bi-calendar-plus', 'roles' => ['admin']],
    ['label' => 'Role Permission', 'route' => 'settings.roles', 'icon' => 'bi-shield-lock', 'roles' => ['admin']],
    ['label' => 'Email Settings', 'route' => 'settings.email', 'icon' => 'bi-envelope-gear', 'roles' => ['admin']],
    ['label' => 'SMS Settings', 'route' => 'settings.sms', 'icon' => 'bi-phone', 'roles' => ['admin']],
    ['label' => 'Payment Method Settings', 'route' => 'payment-methods.index', 'icon' => 'bi-credit-card-2-front', 'roles' => ['admin']],
    ['label' => 'Weekend Setup', 'route' => 'settings.weekend', 'icon' => 'bi-calendar-x', 'roles' => ['admin']],
    ['label' => 'Language Settings', 'route' => 'settings.language', 'icon' => 'bi-translate', 'roles' => ['admin']],
    ['label' => 'Backup', 'route' => 'settings.backup', 'icon' => 'bi-hdd', 'roles' => ['admin']],
    ['label' => 'User Management', 'route' => 'users.index', 'icon' => 'bi-people-fill', 'roles' => ['admin']],

    ['section' => 'Front CMS', 'roles' => ['admin']],
    ['label' => 'Header Menu', 'route' => 'cms-menus.index', 'icon' => 'bi-menu-button-wide', 'roles' => ['admin']],
    ['label' => 'News Categories', 'route' => 'news-categories.index', 'icon' => 'bi-newspaper', 'roles' => ['admin']],
    ['label' => 'News', 'route' => 'news.index', 'icon' => 'bi-newspaper', 'roles' => ['admin']],
    ['label' => 'Course Categories', 'route' => 'course-categories.index', 'icon' => 'bi-mortarboard', 'roles' => ['admin']],
    ['label' => 'Courses', 'route' => 'courses.index', 'icon' => 'bi-mortarboard-fill', 'roles' => ['admin']],
    ['label' => 'Testimonials', 'route' => 'testimonials.index', 'icon' => 'bi-chat-quote', 'roles' => ['admin']],
    ['label' => 'Contact Messages', 'route' => 'contact-messages.index', 'icon' => 'bi-envelope-open', 'roles' => ['admin']],
    ['label' => 'Social Links', 'route' => 'social-links.index', 'icon' => 'bi-share', 'roles' => ['admin']],
    ['label' => 'Pages', 'route' => 'pages.index', 'icon' => 'bi-file-earmark-plus', 'roles' => ['admin']],
    ['label' => 'Footer Widgets', 'route' => 'footer-widgets.index', 'icon' => 'bi-layout-text-window-reverse', 'roles' => ['admin']],

    ['section' => 'My Panel', 'roles' => ['teacher', 'student', 'parent']],
    ['label' => 'My Class Routine', 'route' => 'panel.routine', 'icon' => 'bi-calendar3-week', 'roles' => ['student', 'parent']],
    ['label' => 'Exam Marks', 'route' => 'panel.marks', 'icon' => 'bi-journal-check', 'roles' => ['student', 'parent']],
    ['label' => 'Attendance Status', 'route' => 'panel.attendance', 'icon' => 'bi-check2-square', 'roles' => ['student', 'parent']],
    ['label' => 'Exam Results', 'route' => 'panel.results', 'icon' => 'bi-file-earmark-bar-graph', 'roles' => ['student', 'parent']],
    ['label' => 'Payment Invoices', 'route' => 'panel.invoices', 'icon' => 'bi-receipt', 'roles' => ['student', 'parent']],
    ['label' => 'My Students', 'route' => 'panel.students', 'icon' => 'bi-people', 'roles' => ['teacher']],
    ['label' => 'My Profile', 'route' => 'panel.profile', 'icon' => 'bi-person-circle', 'roles' => ['admin', 'accountant', 'teacher', 'student', 'parent']],
];
